<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsSeederTable extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->delete();
        DB::table('depots')->delete();

        // DB::table('products')->insert(array (
        //     0 =>
        //         array (
        //             'id'=>1,
        //             'reference'=> 'BSD-0021-C',
        //             'title'=>'Boutique Silk Dress',
        //             'slug'=>'boutique-silk-dress',
        //             'description'=>'<p>Enquête portant sur l’éducation et la qualité de vie des habitants de Richard-Toll.</p>',
        //             'stock'=>20,
        //             'brand_id'=>1,
        //             'cat_id'=>1,
        //             'user_id'=>1,
        //             'fournisseur_id'=>1,
        //             'child_cat_id'=>null,
        //             'photo'=>'frontend/assets/img/product-img/new-1-back.png',
        //             'type'=>'Numerique',
        //             'buying_price'=>100,
        //             'price'=>50,
        //             'offer_price'=>45,
        //             'conditions'=>'vendre',
        //             'added_by'=>'admin',
        //             'status'=>'active',
        //             'created_at'=>Carbon::now(),
        //             'updated_at'=>Carbon::now(),
        //         ),
        //     1 =>
        //         array (
        //             'id'=>2,
        //             'reference'=> 'FTD-0421-C',
        //             'title'=>'Flower Textured Dress',
        //             'slug'=>'flower-textured-dress',
        //             'description'=>'<p>Enquête portant sur l’éducation et la qualité de vie des habitants de Richard-Toll.</p>',
        //             'stock'=>20,
        //             'brand_id'=>2,
        //             'cat_id'=>2,
        //             'user_id'=>1,
        //             'fournisseur_id'=>1,
        //             'child_cat_id'=>null,
        //             'photo'=>'frontend/assets/img/product-img/new-2-back.png',
        //             'type'=>'Numerique',
        //             'buying_price'=>100,
        //             'price'=>48,
        //             'offer_price'=>34,
        //             'conditions'=>'vedette',
        //             'added_by'=>'admin',
        //             'status'=>'active',
        //             'created_at'=>Carbon::now(),
        //             'updated_at'=>Carbon::now(),
        //         ),
        //     2 =>
        //         array (
        //             'id'=>3,
        //             'reference'=> 'SD-3422-C',
        //             'title'=>'Silk Dress',
        //             'slug'=>'silk-dress',
        //             'description'=>'<p>Enquête portant sur l’éducation et la qualité de vie des habitants de Richard-Toll.</p>',
        //             'stock'=>20,
        //             'brand_id'=>3,
        //             'cat_id'=>3,
        //             'user_id'=>1,
        //             'fournisseur_id'=>1,
        //             'child_cat_id'=>null,
        //             'photo'=>'frontend/assets/img/product-img/new-3-back.png',
        //             'type'=>'Numerique',
        //             'buying_price'=>100,
        //             'price'=>50,
        //             'offer_price'=>96,
        //             'conditions'=>'vendre',
        //             'added_by'=>'admin',
        //             'status'=>'active',
        //             'created_at'=>Carbon::now(),
        //             'updated_at'=>Carbon::now(),
        //         ),
        //     3 =>
        //         array (
        //             'id'=>4,
        //             'reference'=> 'BSD-4312-C',
        //             'title'=>'Box Shape Dress',
        //             'slug'=>'box-shape-dress',
        //             'description'=>'<p>Enquête portant sur l’éducation et la qualité de vie des habitants de Richard-Toll.</p>',
        //             'stock'=>20,
        //             'brand_id'=>1,
        //             'cat_id'=>1,
        //             'user_id'=>1,
        //             'fournisseur_id'=>1,
        //             'child_cat_id'=>null,
        //             'photo'=>'frontend/assets/img/product-img/new-4-back.png',
        //             'type'=>'Numerique',
        //             'buying_price'=>100,
        //             'price'=>50,
        //             'offer_price'=>96,
        //             'conditions'=>'vendre',
        //             'added_by'=>'admin',
        //             'status'=>'active',
        //             'created_at'=>Carbon::now(),
        //             'updated_at'=>Carbon::now(),
        //         ),
        //     4 =>
        //         array (
        //             'id'=>5,
        //             'reference'=> 'FD-6653-C',
        //             'title'=>'Fashion Dress',
        //             'slug'=>'fashion-dress',
        //             'description'=>'<p>Enquête portant sur l’éducation et la qualité de vie des habitants de Richard-Toll.</p>',
        //             'stock'=>20,
        //             'brand_id'=>2,
        //             'cat_id'=>2,
        //             'user_id'=>1,
        //             'fournisseur_id'=>1,
        //             'child_cat_id'=>null,
        //             'photo'=>'frontend/assets/img/product-img/new-5-back.png',
        //             'type'=>'Numerique',
        //             'buying_price'=>100,
        //             'price'=>50,
        //             'offer_price'=>96,
        //             'conditions'=>'vendre',
        //             'added_by'=>'admin',
        //             'status'=>'active',
        //             'created_at'=>Carbon::now(),
        //             'updated_at'=>Carbon::now(),
        //         ),
        //     5 =>
        //         array (
        //             'id'=>6,
        //             'title'=>'Textured Dress',
        //             'reference'=> 'TD-3321-C',
        //             'slug'=>'textured-dress',
        //             'description'=>'<p>Enquête portant sur l’éducation et la qualité de vie des habitants de Richard-Toll.</p>',
        //             'stock'=>20,
        //             'brand_id'=>2,
        //             'cat_id'=>3,
        //             'user_id'=>1,
        //             'fournisseur_id'=>1,
        //             'child_cat_id'=>null,
        //             'photo'=>'frontend/assets/img/product-img/new-6-back.png',
        //             'type'=>'Numerique',
        //             'buying_price'=>100,
        //             'price'=>50,
        //             'offer_price'=>96,
        //             'conditions'=>'vedette',
        //             'added_by'=>'admin',
        //             'status'=>'active',
        //             'created_at'=>Carbon::now(),
        //             'updated_at'=>Carbon::now(),
        //         ),
        //     6 =>
        //         array (
        //             'id'=>7,
        //             'reference'=> 'RD-8743-C',
        //             'title'=>'Right Dress',
        //             'slug'=>'right-dress',
        //             'description'=>'<p>Enquête portant sur l’éducation et la qualité de vie des habitants de Richard-Toll.</p>',
        //             'stock'=>20,
        //             'brand_id'=>3,
        //             'cat_id'=>2,
        //             'user_id'=>1,
        //             'fournisseur_id'=>1,
        //             'child_cat_id'=>null,
        //             'photo'=>'frontend/assets/img/product-img/new-7-back.png',
        //             'type'=>'Numerique',
        //             'buying_price'=>100,
        //             'price'=>50,
        //             'offer_price'=>96,
        //             'conditions'=>'vendre',
        //             'added_by'=>'admin',
        //             'status'=>'active',
        //             'created_at'=>Carbon::now(),
        //             'updated_at'=>Carbon::now(),
        //         ),
        //     7 =>
        //         array (
        //             'id'=>8,
        //             'reference'=> 'WD-0342-C',
        //             'title'=>'Width Dress',
        //             'slug'=>'width-dress',
        //             'description'=>'<p>Enquête portant sur l’éducation et la qualité de vie des habitants de Richard-Toll.</p>',
        //             'stock'=>20,
        //             'brand_id'=>4,
        //             'cat_id'=>1,
        //             'user_id'=>1,
        //             'fournisseur_id'=>1,
        //             'child_cat_id'=>null,
        //             'photo'=>'frontend/assets/img/product-img/new-8-back.png',
        //             'type'=>'Numerique',
        //             'buying_price'=>100,
        //             'price'=>50,
        //             'offer_price'=>96,
        //             'conditions'=>'vendre',
        //             'added_by'=>'admin',
        //             'status'=>'active',
        //             'created_at'=>Carbon::now(),
        //             'updated_at'=>Carbon::now(),
        //         ),
        //     8 =>
        //         array (
        //             'id'=>9,
        //             'reference'=> 'DD-4455-C',
        //             'title'=>'Dark Dress',
        //             'slug'=>'dark-dress',
        //             'description'=>'<p>Enquête portant sur l’éducation et la qualité de vie des habitants de Richard-Toll.</p>',
        //             'stock'=>20,
        //             'brand_id'=>1,
        //             'cat_id'=>1,
        //             'user_id'=>1,
        //             'fournisseur_id'=>1,
        //             'child_cat_id'=>null,
        //             'photo'=>'frontend/assets/img/product-img/new-3.png',
        //             'type'=>'Numerique',
        //             'buying_price'=>100,
        //             'price'=>150,
        //             'offer_price'=>0,
        //             'conditions'=>'vendre',
        //             'added_by'=>'admin',
        //             'status'=>'active',
        //             'created_at'=>Carbon::now(),
        //             'updated_at'=>Carbon::now(),
        //         ),

        // ));

        // DB::table('depots')->insert(array (
        //     0 =>
        //         array (
        //             'id'=>1,
        //             'reference'=> 'BSD-0021-C',
        //             'nom'=>'Boutique Silk Dress',
        //             'stock'=>200,
        //             'fournisseur_id'=>1,
        //             'photo'=>'frontend/assets/img/product-img/new-1-back.png',
        //             'statut'=>'activer',
        //             'created_at'=>Carbon::now(),
        //             'updated_at'=>Carbon::now(),
        //         ),
        //     1 =>
        //         array (
        //             'id'=>2,
        //             'reference'=> 'FTD-0421-C',
        //             'nom'=>'Flower Textured Dress',
        //             'stock'=>100,
        //             'fournisseur_id'=>1,
        //             'photo'=>'frontend/assets/img/product-img/new-2-back.png',
        //             'statut'=>'activer',
        //             'created_at'=>Carbon::now(),
        //             'updated_at'=>Carbon::now(),
        //         ),
        //     2 =>
        //         array (
        //             'id'=>3,
        //             'reference'=> 'SD-3422-C',
        //             'nom'=>'Silk Dress',
        //             'stock'=>150,
        //             'fournisseur_id'=>1,
        //             'photo'=>'frontend/assets/img/product-img/new-3-back.png',
        //             'statut'=>'activer',
        //             'created_at'=>Carbon::now(),
        //             'updated_at'=>Carbon::now(),
        //         ),
        //     3 =>
        //         array (
        //             'id'=>4,
        //             'reference'=> 'BSD-4312-C',
        //             'nom'=>'Box Shape Dress',
        //             'stock'=>20,
        //             'fournisseur_id'=>1,
        //             'photo'=>'frontend/assets/img/product-img/new-4-back.png',
        //             'statut'=>'activer',
        //             'created_at'=>Carbon::now(),
        //             'updated_at'=>Carbon::now(),
        //         ),
        //     4 =>
        //         array (
        //             'id'=>5,
        //             'reference'=> 'FD-6653-C',
        //             'nom'=>'Fashion Dress',
        //             'stock'=>200,
        //             'fournisseur_id'=>1,
        //             'photo'=>'frontend/assets/img/product-img/new-5-back.png',
        //             'statut'=>'activer',
        //             'created_at'=>Carbon::now(),
        //             'updated_at'=>Carbon::now(),
        //         ),
        //     5 =>
        //         array (
        //             'id'=>6,
        //             'nom'=>'Textured Dress',
        //             'reference'=> 'TD-3321-C',
        //             'stock'=>200,
        //             'fournisseur_id'=>1,
        //             'photo'=>'frontend/assets/img/product-img/new-6-back.png',
        //             'statut'=>'activer',
        //             'created_at'=>Carbon::now(),
        //             'updated_at'=>Carbon::now(),
        //         ),
        //     6 =>
        //         array (
        //             'id'=>7,
        //             'reference'=> 'RD-8743-C',
        //             'nom'=>'Right Dress',
        //             'stock'=>200,
        //             'fournisseur_id'=>1,
        //             'photo'=>'frontend/assets/img/product-img/new-7-back.png',
        //             'statut'=>'activer',
        //             'created_at'=>Carbon::now(),
        //             'updated_at'=>Carbon::now(),
        //         ),
        //     7 =>
        //         array (
        //             'id'=>8,
        //             'reference'=> 'WD-0342-C',
        //             'nom'=>'Width Dress',
        //             'stock'=>200,
        //             'fournisseur_id'=>1,
        //             'photo'=>'frontend/assets/img/product-img/new-8-back.png',
        //             'statut'=>'activer',
        //             'created_at'=>Carbon::now(),
        //             'updated_at'=>Carbon::now(),
        //         ),
        //     8 =>
        //         array (
        //             'id'=>9,
        //             'reference'=> 'DD-4455-C',
        //             'nom'=>'Dark Dress',
        //             'stock'=>200,
        //             'fournisseur_id'=>1,
        //             'photo'=>'frontend/assets/img/product-img/new-3.png',
        //             'statut'=>'activer',
        //             'created_at'=>Carbon::now(),
        //             'updated_at'=>Carbon::now(),
        //         ),

        // ));

    }
}
